services:
  vllm:
    image: rocm/vllm-dev:nightly
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
      - render
    ipc: host
    ports:
      - "8000:8000"
    cap_add:
      - SYS_PTRACE
    volumes:
      - /home/virobles/google/gemma-3-27b-it:/model
    restart: unless-stopped
    command: >
        vllm serve /model
        --served-model-name google/gemma-3-27b-it
        --max-model-len 8192
        --gpu-memory-utilization 0.96
        --host 0.0.0.0
        --dtype bfloat16
        --enforce-eager