version: "3.9"

services:
  vllm:
    image: rocm/vllm-dev:nightly
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
      - render
    ipc: host
    ports:
      - "8000:8000"
    cap_add:
      - SYS_PTRACE
    volumes:
      - /home/virobles/google/gemma-3-27b-it:/google/gemma-3-27b-it
    command:
      - /bin/sh
      - -c
      - >
        vllm serve /google/gemma-3-27b-it
        --max-model-len 4096
        --limit-mm-per-prompt '{"image":2}'
        --dtype bfloat16
        --enforce-eager
